export const CATEGORY_LIST = 'CATEGORY_LIST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const CATEGORY_DETAIL = 'CATEGORY_DETAIL'
export const CATEGORY_DETAIL_SUCCESS = 'CATEGORY_DETAIL_SUCCESS'
export const CATEGORY_DETAIL_FAIL = 'CATEGORY_DETAIL_FAIL'

export const CATEGORY_SAVE = 'CATEGORY_SAVE'
export const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS'
export const CATEGORY_SAVE_FAIL = 'CATEGORY_SAVE_FAIL'

export const CATEGORY_UPDATE = 'CATEGORY_UPDATE'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'

export const CATEGORY_DELETE = 'CATEGORY_DELETE'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'

export const CATEGORY_DELETE_LIST = 'CATEGORY_DELETE_LIST'
export const CATEGORY_DELETE_LIST_SUCCESS = 'CATEGORY_DELETE_LIST_SUCCESS'
export const CATEGORY_DELETE_LIST_FAIL = 'CATEGORY_DELETE_LIST_FAIL'

export const CATEGORY_CLEAN_FAIL = 'CATEGORY_CLEAN_FAIL'
export const CATEGORY_CLEAN_SUCCESS = 'CATEGORY_CLEAN_SUCCESS'
