export const ITEM_LIST = 'ITEM_LIST'
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL'

export const ITEM_DETAIL = 'ITEM_DETAIL'
export const ITEM_DETAIL_SUCCESS = 'ITEM_DETAIL_SUCCESS'
export const ITEM_DETAIL_FAIL = 'ITEM_DETAIL_FAIL'

export const ITEM_SAVE = 'ITEM_SAVE'
export const ITEM_SAVE_SUCCESS = 'ITEM_SAVE_SUCCESS'
export const ITEM_SAVE_FAIL = 'ITEM_SAVE_FAIL'

export const ITEM_UPDATE = 'ITEM_UPDATE'
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS'
export const ITEM_UPDATE_FAIL = 'ITEM_UPDATE_FAIL'

export const ITEM_DELETE = 'ITEM_DELETE'
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS'
export const ITEM_DELETE_FAIL = 'ITEM_DELETE_FAIL'

export const ITEM_DELETE_LIST = 'ITEM_DELETE_LIST'
export const ITEM_DELETE_LIST_SUCCESS = 'ITEM_DELETE_LIST_SUCCESS'
export const ITEM_DELETE_LIST_FAIL = 'ITEM_DELETE_LIST_FAIL'

export const ITEM_CLEAN_FAIL = 'ITEM_CLEAN_FAIL'
export const ITEM_CLEAN_SUCCESS = 'ITEM_CLEAN_SUCCESS'
