export const STOCK_OUT_LIST = 'STOCK_OUT_LIST'
export const STOCK_OUT_LIST_SUCCESS = 'STOCK_OUT_LIST_SUCCESS'
export const STOCK_OUT_LIST_FAIL = 'STOCK_OUT_LIST_FAIL'

export const STOCK_OUT_DETAIL = 'STOCK_OUT_DETAIL'
export const STOCK_OUT_DETAIL_SUCCESS = 'STOCK_OUT_DETAIL_SUCCESS'
export const STOCK_OUT_DETAIL_FAIL = 'STOCK_OUT_DETAIL_FAIL'

export const STOCK_OUT_SAVE = 'STOCK_OUT_SAVE'
export const STOCK_OUT_SAVE_SUCCESS = 'STOCK_OUT_SAVE_SUCCESS'
export const STOCK_OUT_SAVE_FAIL = 'STOCK_OUT_SAVE_FAIL'

export const STOCK_OUT_UPDATE = 'STOCK_OUT_UPDATE'
export const STOCK_OUT_UPDATE_SUCCESS = 'STOCK_OUT_UPDATE_SUCCESS'
export const STOCK_OUT_UPDATE_FAIL = 'STOCK_OUT_UPDATE_FAIL'

export const STOCK_OUT_DELETE = 'STOCK_OUT_DELETE'
export const STOCK_OUT_DELETE_SUCCESS = 'STOCK_OUT_DELETE_SUCCESS'
export const STOCK_OUT_DELETE_FAIL = 'STOCK_OUT_DELETE_FAIL'

export const STOCK_OUT_DELETE_LIST = 'STOCK_OUT_DELETE_LIST'
export const STOCK_OUT_DELETE_LIST_SUCCESS = 'STOCK_OUT_DELETE_LIST_SUCCESS'
export const STOCK_OUT_DELETE_LIST_FAIL = 'STOCK_OUT_DELETE_LIST_FAIL'

export const STOCK_OUT_CLEAN_FAIL = 'STOCK_OUT_CLEAN_FAIL'
export const STOCK_OUT_CLEAN_SUCCESS = 'STOCK_OUT_CLEAN_SUCCESS'
