export const STOCK_LIST = 'STOCK_LIST'
export const STOCK_LIST_SUCCESS = 'STOCK_LIST_SUCCESS'
export const STOCK_LIST_FAIL = 'STOCK_LIST_FAIL'

export const STOCK_DETAIL = 'STOCK_DETAIL'
export const STOCK_DETAIL_SUCCESS = 'STOCK_DETAIL_SUCCESS'
export const STOCK_DETAIL_FAIL = 'STOCK_DETAIL_FAIL'

export const STOCK_SAVE = 'STOCK_SAVE'
export const STOCK_SAVE_SUCCESS = 'STOCK_SAVE_SUCCESS'
export const STOCK_SAVE_FAIL = 'STOCK_SAVE_FAIL'

export const STOCK_UPDATE = 'STOCK_UPDATE'
export const STOCK_UPDATE_SUCCESS = 'STOCK_UPDATE_SUCCESS'
export const STOCK_UPDATE_FAIL = 'STOCK_UPDATE_FAIL'

export const STOCK_DELETE = 'STOCK_DELETE'
export const STOCK_DELETE_SUCCESS = 'STOCK_DELETE_SUCCESS'
export const STOCK_DELETE_FAIL = 'STOCK_DELETE_FAIL'

export const STOCK_DELETE_LIST = 'STOCK_DELETE_LIST'
export const STOCK_DELETE_LIST_SUCCESS = 'STOCK_DELETE_LIST_SUCCESS'
export const STOCK_DELETE_LIST_FAIL = 'STOCK_DELETE_LIST_FAIL'

export const STOCK_REPORT_LIST = 'STOCK_REPORT_LIST'
export const STOCK_REPORT_LIST_FAIL = 'STOCK_REPORT_LIST_FAIL'
export const STOCK_REPORT_LIST_SUCCESS = 'STOCK_REPORT_LIST_SUCCESS'

export const STOCK_REPORT_DETAIL = 'STOCK_REPORT_DETAIL'
export const STOCK_REPORT_DETAIL_FAIL = 'STOCK_REPORT_DETAIL_FAIL'
export const STOCK_REPORT_DETAIL_SUCCESS = 'STOCK_REPORT_DETAIL_SUCCESS'

export const STOCK_DETAIL_LIST = 'STOCK_DETAIL_LIST'
export const STOCK_DETAIL_LIST_FAIL = 'STOCK_DETAIL_LIST_FAIL'
export const STOCK_DETAIL_LIST_SUCCESS = 'STOCK_DETAIL_LIST_SUCCESS'

export const STOCK_CLEAN_FAIL = 'STOCK_CLEAN_FAIL'
export const STOCK_CLEAN_SUCCESS = 'STOCK_CLEAN_SUCCESS'
