export const STOCK_IN_LIST = 'STOCK_IN_LIST'
export const STOCK_IN_LIST_SUCCESS = 'STOCK_IN_LIST_SUCCESS'
export const STOCK_IN_LIST_FAIL = 'STOCK_IN_LIST_FAIL'

export const STOCK_IN_DETAIL = 'STOCK_IN_DETAIL'
export const STOCK_IN_DETAIL_SUCCESS = 'STOCK_IN_DETAIL_SUCCESS'
export const STOCK_IN_DETAIL_FAIL = 'STOCK_IN_DETAIL_FAIL'

export const STOCK_IN_SAVE = 'STOCK_IN_SAVE'
export const STOCK_IN_SAVE_SUCCESS = 'STOCK_IN_SAVE_SUCCESS'
export const STOCK_IN_SAVE_FAIL = 'STOCK_IN_SAVE_FAIL'

export const STOCK_IN_UPDATE = 'STOCK_IN_UPDATE'
export const STOCK_IN_UPDATE_SUCCESS = 'STOCK_IN_UPDATE_SUCCESS'
export const STOCK_IN_UPDATE_FAIL = 'STOCK_IN_UPDATE_FAIL'

export const STOCK_IN_DELETE = 'STOCK_IN_DELETE'
export const STOCK_IN_DELETE_SUCCESS = 'STOCK_IN_DELETE_SUCCESS'
export const STOCK_IN_DELETE_FAIL = 'STOCK_IN_DELETE_FAIL'

export const STOCK_IN_DELETE_LIST = 'STOCK_IN_DELETE_LIST'
export const STOCK_IN_DELETE_LIST_SUCCESS = 'STOCK_IN_DELETE_LIST_SUCCESS'
export const STOCK_IN_DELETE_LIST_FAIL = 'STOCK_IN_DELETE_LIST_FAIL'

export const STOCK_IN_CLEAN_FAIL = 'STOCK_IN_CLEAN_FAIL'
export const STOCK_IN_CLEAN_SUCCESS = 'STOCK_IN_CLEAN_SUCCESS'
