export const USER_LIST = 'USER_LIST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const USER_DETAIL = 'USER_DETAIL'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'

export const USER_SAVE = 'USER_SAVE'
export const USER_SAVE_SUCCESS = 'USER_SAVE_SUCCESS'
export const USER_SAVE_FAIL = 'USER_SAVE_FAIL'

export const USER_UPDATE = 'USER_UPDATE'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const USER_DELETE = 'USER_DELETE'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_DELETE_LIST = 'USER_DELETE_LIST'
export const USER_DELETE_LIST_SUCCESS = 'USER_DELETE_LIST_SUCCESS'
export const USER_DELETE_LIST_FAIL = 'USER_DELETE_LIST_FAIL'

export const USER_CLEAN_FAIL = 'USER_CLEAN_FAIL'
export const USER_CLEAN_SUCCESS = 'USER_CLEAN_SUCCESS'
